import { Montserrat } from "next/font/google";
import "./globals.css";

const montserrat = Montserrat({ subsets: ["latin"] });

export const metadata = {
  title: "Simmons Casa Orner",
  description: "Generated by create next app",
  icons: {
    icon: './favicon.png', // /public path
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br" className=" !scroll-smooth">
      <head>
      <link href="https://cdn.jsdelivr.net/npm/flowbite@2.4.1/dist/flowbite.min.css" rel="stylesheet" />
      
      </head>
      <body className={montserrat.className} >
        {children}
      <script src="https://cdn.jsdelivr.net/npm/flowbite@2.4.1/dist/flowbite.min.js"></script>
      </body>
    </html>
  );
}
